# Generated by Django 4.0 on 2022-04-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='daromadi',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
