# Generated by Django 4.0 on 2022-04-02 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_post_image_post_korsatkich_post_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='year',
        ),
    ]
