# Generated by Django 4.0 on 2022-04-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_post_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='korsatkich',
            new_name='miqdori',
        ),
    ]
