# Generated by Django 4.0 on 2022-04-02 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_korsatkich_post_miqdori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='miqdori',
            new_name='mazmuni',
        ),
    ]
