# Generated by Django 4.0 on 2022-04-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_miqdori_post_mazmuni'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mazmuni',
            new_name='korsatkichi',
        ),
    ]
