# Generated by Django 4.0 on 2022-04-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_mazmuni_post_korsatkichi'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
